### ISSUE TITLE
Fit machen für 3.5 LTS

### ISSUE THREAD

**Issue by csaeum** [netzmacht/contao-timelinejs#1]
Ich habe es gerade in Contao 3.5 LTS installiert.

Er lädt hier die Daten ewig, und zeigt somit nichts an. Machst du diese Fit für 3.5?

**Comment by dmolineus** [comment]
Bin mir nicht sicher, ob es eine 3.5 Inkompatibilität ist. Getestet ist die Erweiterung nohc nicht unter 3.5

**Comment by porzellankompass** [comment]
Unter 3.5.2 funkioniert es bei mir wunderbar.
Allein ich kann den "Reader" nicht mehr "verallgemeinern". Soll heißen, der Reader nimmt immer den ersten Eintrag.
Der Reader möchte eine Zuordnung. Die kann ich später im Artikel nicht mehr überspielen.
Ich denke, ein 3.5.2-Problem

**Comment by dmolineus** [comment]
Das liegt daran, dass eine statsiche ID vergeben wird. Hier müsste man noch die ID des Elements anhängen und dann auch im JS konfigurieren. 

https://github.com/netzmacht/contao-timelinejs/blob/master/src/system/modules/timelinejs/templates/timelinejs.html5#L4

**Comment by dmolineus** [comment]
Inzwischen existiert eine neue Alpha Version 3.0-alpha1 basierend auf TImelineJS 3. Diese läuft problemlos unter 3.5. Die 1er Version wird nicht weiter supportet.
