### ISSUE TITLE
Die "era"s werden nicht richtig dargestellt

### ISSUE THREAD

**Issue by porzellankompass** [netzmacht/contao-timelinejs#2]
Damit die era´s richtig verarbeitet werden, sollten folgende Ergänzungen erfolgen:
        $json = array();
        $json['headline'] = $this->replaceInsertTags($timeline->title);
        $json['type']     = 'default';
        $json['text']     = $this->replaceInsertTags($timeline->teaser);
        $json['date']     = array();
        $json['era']     = array();

und
             if($entries->era) {
            $eraentry = array(
                'startDate' => $entries->startDate,
                'endDate'   => $entries->endDate ? $entries->endDate : $entries->startDate,
                'headline'  => $this->replaceInsertTags($entries->headline),
            );
            $json['era'][] = $eraentry; 
            } 

Dann erscheint die Markierung ohne "Flag".

**Comment by dmolineus** [comment]
Was ist denn genau der Fehler? An sich werden ja die Eras erstellt. Oder übsehe ich etwas?
https://github.com/netzmacht/contao-timelinejs/blob/master/src/system/modules/timelinejs/classes/JSONController.php#L100-L113

**Comment by porzellankompass** [comment]
@dmolineus 
nein, natürlich nicht. Aber die "era"´s werden in der Schleife über die Einträge immer mit einem "Flag" versehen. Das heißt, zu jedem Eintrag "era" erhalte ich ich immer auch einen Eintrag "Flag". Das war nicht die Idee von timelinejs. Die "era"´s sind eine Hintergrundinfo. Und sortieren sich farblich sortiert entsprechend ein.
Also sollte ich die "era"´s vorher herausholen.
Wenn ich die "era"´s vorher über ein {if} rausfische und sie in ein eigenes Array sperre, werden sie timelinejs-konform dargestellt.
Unter contao 3.5.2 habe ich jedenfalls diesen Effekt.
Ein entsprechendes {if} zu Anfang der Schleife funktioniert wunderbar. Mein JSON-Controller.php sieht z.zT. so aus:

<?php

/**
- Contao Open Source CMS
  *
- Copyright (C) 2005-2013 Leo Feyer
  *
- @package   timelinejs
- @author    netzmacht creative David Molineus
- @license   MPL/2.0
- @copyright 2013 netzmacht creative David Molineus
  */

namespace Netzmacht\TimelineJS;

/**
- Class JSONController
- @package Netzmacht\TimelineJS
  */
  class JSONController extends \Frontend
  {
  
  /**
  - initialize controller
    */
    public function __construct()
    {
    $this->import('BackendUser', 'User');
    parent::__construct();
    
    $this->loadLanguageFile('default');
    $this->loadLanguageFile('modules');
    $this->setStaticUrls();
    }
  
  /**
  - generates the json array of a timeline
  - @throws \Exception
    */
    public function run()
    {
    $id = \Input::get('id');
    
    if($id == '')
    {
        throw new \Exception('No id given');
    }
    
    echo $this->createJson($id);
    }
  
  /**
  - create cache entry and return it as string
  - @param $id
  - @return string
  - @throws \Exception
    */
    public function createJson($id)
    {
    $timeline = \TimelineJSModel::findByPk($id);
    $entries  = \TimelineJSEntryModel::findPublishedByPid($id);
    
    if($timeline === null)
    {
        throw new \Exception('Timeline not found');
    }
    
    $json = array();
    $json['headline'] = $this->replaceInsertTags($timeline->title);
    $json['type']     = 'default';
    $json['text']     = $this->replaceInsertTags($timeline->teaser);
    $json['date']     = array();
    /*\* neues Array era, soweit so gut, gehoert aber auch zu json, wird also veröffentlicht  **/
    $json['era']     = array();
    
    if($timeline->media)
    {
        $json['asset'] = array
        (
            'credit'  => $this->replaceInsertTags($timeline->credit),
            'caption' => $this->replaceInsertTags($timeline->caption)
        );
    
    ```
    if($timeline->singleSRC)
    {
        $objFile = \FilesModel::findByPk($timeline->singleSRC);
        $json['asset']['media'] = $objFile->path;
    }
    ```
    
    }
    
    if($entries === null)
    {
        echo json_encode($json);
        return '';
    }
    
    while($entries->next()) {
    /*\* ich beginne zu fischen **/
         if($entries->era) {
    
    ```
    $eraentry = array(
        'startDate' => $entries->startDate,
        'endDate'   => $entries->endDate ? $entries->endDate : $entries->startDate,
        'headline'  => $this->replaceInsertTags($entries->headline),
    );
    $json['era'][] = $eraentry; 
    } 
    ```
    
    /*\* fertig mit fischen, ansonsten ein normaler Eintrag **//
        else {
            $entry = array(
            'startDate' => $entries->startDate,
            'endDate'   => $entries->endDate ? $entries->endDate : $entries->startDate,
            'headline'  => $this->replaceInsertTags($entries->headline),
            'text'      => $this->replaceInsertTags($entries->teaser),
        );
        }
    
    ```
    if($entries->tags) {
        $entry['tag'] = $entries->tags;
    }
    
    
    if($entries->media) {
        $thumbnail = false;
    
        if($entries->thumbnail) {
            $objFile   = \FilesModel::findByPk($entries->thumbnail);
            $thumbnail = \Image::get($objFile->path, 60, 60);
        }
    
        if($entries->singleSRC) {
            $objFile = \FilesModel::findByPk($entries->singleSRC);
            $url = $objFile->path;
    
            if(!$thumbnail)
            {
                $thumbnail = \Image::get($url, 60, 60);
            }
        }
        else {
            $url = $this->replaceInsertTags($entries->url);
        }
    
        $entry['asset'] = array(
            'media'   => $url,
            'credit'  => $this->replaceInsertTags($entries->credit),
            'caption' => $this->replaceInsertTags($entries->caption),
        );
    
        if($thumbnail)
        {
            $entry['asset']['thumbnail'] = $thumbnail;
        }
    }
    
    $json['date'][] = $entry;
    ```
    
    }
    
    $json = sprintf('{ "timeline": %s }', json_encode($json));
    return $json;
    }
    }

Ich hoffe, Sie können damit etwas anfangen. Leider bin ich neu auf git, sodaß Formatierung und Antwort etwas ungelenk sein können.

**Comment by porzellankompass** [comment]
@dmolineus 
ich habe noch ein zweites Darstellungsproblem:
unter Contao 3.5.2 lts kann ich z.Zt. nur >>>eine<<< timeline auf der Site darstellen. Der Reader verlangt immer eine Zuordnung zu EINER timeline. In der Seitenzuordnung kann ich etwas anderes einstellen, allein der Reader will - eine - Zuordnung. Von der er sich nicht mehr abringen lässt. Wahrscheinlich ein 3.5.2-Problem.
Das war wohl nicht die Idee.
Ursache habe ich leider noch nicht gefunden.
z.Zt. Contao 3.5.2 local
btw: gibt es Überlegungen auf timelinejs3 aufzurüsten?

**Comment by dmolineus** [comment]
Ok, jetzt verstehe ich dein Anliegen. :) 

War in den Kundenprojekt, in der die Erweiterung entstanden ist, so gewünscht. Man kann aber die Einstellungen so erweitern, dass beide Verhaltensweisen möglich werden.

**Comment by dmolineus** [comment]
Inzwischen existiert eine neue Alpha-Version, die auf TimelineJS 3.0 basiert. Hier können Eras separat angelegt werden.
