### ISSUE TITLE
Insert-Tags: Pfade werden nicht korrekt ausgegeben.

### ISSUE THREAD

**Issue by savuti** [netzmacht/contao-timelinejs#4]
Hallo David,

in der Alpha 2 wird, bei Nutzung von Inserttags, zusätzlich zum Pfad davor noch "TL_FILES_URL" ausgegeben. Das Problem wurde auch schon im Forum für Version 1 beschrieben und gelöst/geflickt. Jedoch hat sich die Struktur in der 3er Version geändert, sodass die Lösung hier nicht mehr funktioniert.

Zur Erinnerung:
`<img src="**TL_FILES_URL**files/dir/dir/bild.jpg">`

**Comment by dmolineus** [comment]
Should be fixed with d0d2d91f37326f302e0014b93be2bca9bc81d9c5. Would be great of you confirm it works by using the lastest dev-develop branch.

**Comment by savuti** [comment]
In der Alpha2 funktioniert das wunderbar. Danke für die schnelle Hilfe. Die dev schaue ich mir an.
